development:
 adapter: postgresql
 encoding: unicode
 database: PortfolioApp_development
 pool: 5
 username: fakedev
 password: password

test:
 adapter: postgresql
 encoding: unicode
 database: PortfolioApp_test
 pool: 5
 username: fakedev
 password: password